### PR TITLE
fix: device.available_climate_presets name type not undefined

### PR DESCRIPTION
**Pull request by mikewuu**
Accidentally merged https://github.com/seamapi/types/pull/1113 without updating the PR title and it didn't release.

This PR just adds the title.

### CODE REVIEW

**Review by andrii-balitskyi — APPROVED** [review]

**Comment by mikewuu** [comment]
damn still didn't work.

CleanShot 2024-09-27 at 20 26 59@2x

@andrii-balitskyi any idea how to get this merged? 😄

**Comment by andrii-balitskyi** [comment]
Hmm not sure. Maybe create a new PR and push a signed commit? https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification

**Comment by razor-x** [comment]
Use the version action to release a new version. Closing this one

**Comment by razor-x** [comment]
Publishing now. See here for next time https://github.com/seamapi/types?tab=readme-ov-file#manual

**Pull request closed without merging**
